### ISSUE TITLE
"verificationMethod property is OPTIONAL" not honored

### ISSUE THREAD

**Issue by letmaik** [OwnYourData/didlint#1]
> Error in validating DID Document:
verificationMethod: Less than 1 values

did-core allows this property to be missing but the linter requires it.

**Comment by fabianekc** [comment]
should validate the following example: https://www.w3.org/TR/did-core/#example-did-document-with-1-verification-method-type

**Comment by fabianekc** [comment]
Making verificationMethod optional while still requiring at least one verification relationship is now available.

old YAML: https://soya.ownyourdata.eu/zQmeCh8bqJWLGYfFz2evRY7MT6QjeSZDyK64h1EdnnYbaGg/yaml
new YAML: https://soya.ownyourdata.eu/zQmcF8QNRakbSThpjxrXNCegUmQqJP2EdsJfXdKvDWCbt8m/yaml
