### ISSUE TITLE
Support JSON representation

### ISSUE THREAD

**Issue by letmaik** [OwnYourData/didlint#2]
The [JSON representation](https://www.w3.org/TR/did-core/#json) in did-core doesn't require a `@context` property.

The linter assumes that the JSON-LD representation is always used and hence shows errors when `@context` is missing:

> @context: missing 'https://www.w3.org/ns/did/v1'

It's probably good practice to always include `@context` anyway, so for me this is a low-priority issue but I wanted to capture it. I'm not sure what the best way is to deal with it.

**Comment by fabianekc** [comment]
should validate the following example: https://www.w3.org/TR/did-core/#example-example-did-document-in-json-representation

**Comment by fabianekc** [comment]
JSON representation of DID documents is now supported, i.e., `@context` is not required anymore. An information is shown instead on the UI / returned as "info" on API level.
