### ISSUE TITLE
How are IPFS links handled?

### ISSUE THREAD

**Issue by ntn-x2** [OwnYourData/didlint#3]
I was trying to browse through the code but could not find an answer. If a context is linked with an IPFS link, in the form of `ipfs://<CID>`, is that supported by the app? Or would the link have to be an HTTP link via a browser, e.g., `https://ipfs.io/ipfs/<CID>`?

**Comment by fabianekc** [comment]
@ntn-x2 Thanks for trying DID Lint!
Can you provide an example DID Document and the expected behaviour? (note: DID Lint is not a resolver and currently only uses the public Uniresolver service for basic DID resolution)

**Comment by ntn-x2** [comment]
I just opened a [Pull Request](https://github.com/decentralized-identity/universal-resolver/pull/349) to update our driver. The latest version returns an additional context which defines exactly the properties that this tool was marking as missing or mistaken. The IPFS gateway address of the context is https://ipfs.io/ipfs/QmU7QkuTCPz7NmD5bD7Z7mQVz2UsSPaEK58B5sYnjnPRNW, but we only used `ipfs://QmU7QkuTCPz7NmD5bD7Z7mQVz2UsSPaEK58B5sYnjnPRNW` in the driver result as we want to leave to the resolver the possibility to use whatever gateway they want. So I was wondering if this would still result in an error from DIDLint when trying to resolve that link to fetch the additional context definition.

**Comment by ntn-x2** [comment]
I guess I got my answer. Our PR was merged, but the error has not gone away, despite the fact that the new terms have been defined in the IPFS-addressed context.
Example DID: `did:kilt:light:014pqDzaWi3w7TzYzGnQDyrasK6UnyNnW6JQvWRrq6r8HzNNGy`

**Comment by fabianekc** [comment]
Pasting the resulting DID Document from `did:kilt:light:014pqDzaWi3w7TzYzGnQDyrasK6UnyNnW6JQvWRrq6r8HzNNGy` into [JSON-LD Playground](https://json-ld.org/playground/) also generates an error: [link](https://json-ld.org/playground/#json-ld=%7B%22id%22%3A%22did%3Akilt%3Alight%3A014pqDzaWi3w7TzYzGnQDyrasK6UnyNnW6JQvWRrq6r8HzNNGy%22%2C%22verificationMethod%22%3A%5B%7B%22id%22%3A%22did%3Akilt%3Alight%3A014pqDzaWi3w7TzYzGnQDyrasK6UnyNnW6JQvWRrq6r8HzNNGy%23authentication%22%2C%22controller%22%3A%22did%3Akilt%3Alight%3A014pqDzaWi3w7TzYzGnQDyrasK6UnyNnW6JQvWRrq6r8HzNNGy%22%2C%22type%22%3A%22Ed25519VerificationKey2018%22%2C%22publicKeyBase58%22%3A%226hwLkCsxFQWcZ2vrmDhyHXjFYJNZPfUqVdkbidW1Sts8%22%7D%5D%2C%22authentication%22%3A%5B%22did%3Akilt%3Alight%3A014pqDzaWi3w7TzYzGnQDyrasK6UnyNnW6JQvWRrq6r8HzNNGy%23authentication%22%5D%2C%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fdid%2Fv1%22%2C%22ipfs%3A%2F%2FQmU7QkuTCPz7NmD5bD7Z7mQVz2UsSPaEK58B5sYnjnPRNW%22%5D%7D%0A)

However, using the following context, it can be parsed nicely:
```
"@context": [
    "https://www.w3.org/ns/did/v1",
    "https://ipfs.io/ipfs/QmU7QkuTCPz7NmD5bD7Z7mQVz2UsSPaEK58B5sYnjnPRNW"
  ]
```

So this should answer the question on the format in context. Agree?

**Comment by ntn-x2** [comment]
Indeed, if the IPFS link is replaced with `https://ipfs.io/ipfs/QmU7QkuTCPz7NmD5bD7Z7mQVz2UsSPaEK58B5sYnjnPRNW`, the expansion works. As far as I have seen, javascript libraries allow to inject a custom `documentLoader` which must contain a mapping from URI scheme to the logic to resolve it, so in this case consumers would probably inject their own resolution logic for IPFS links, which I assume the JSON-LD playground does not do.

**Comment by ntn-x2** [comment]
I would say that specifying the URL of the IPFS gateway is making an opinionated and less-decentralised choice. Probably not the right place to discuss about it here, but since more protocols are relying on decentralised storage infrastructure, forcing an HTTP URL in there is a stretch.

**Comment by fabianekc** [comment]
Do I interpret this correctly that `ipfs://QmU7QkuTCPz7NmD5bD7Z7mQVz2UsSPaEK58B5sYnjnPRNW` is expanded to a JSON that references again HTTP URLs?
```json
{
  "@context": [
    "https://w3id.org/security/v2",
    {
      "@protected": true,
      "KiltPublishedCredentialCollectionV1": "https://github.com/KILTprotocol/spec-KiltPublishedCredentialCollectionV1",
      "Sr25519VerificationKey2020": "https://github.com/KILTprotocol/spec-kilt-did#sr25519"
    }
  ]
}
```

In my understanding of https://www.w3.org/TR/did-spec-registries/#verification-method-types the correct `@context` for `did:kilt` (under the assumption that `"type": "Ed25519VerificationKey2018"` is used in a verification relationship) would be
```json
"@context": [
  "https://www.w3.org/ns/did/v1",
  "https://w3id.org/security/suites/ed25519-2018/v1"
]
```
or alternatively just omit the JSON-LD context all together and use the [JSON representation](https://w3c.github.io/did-core/#json) to be compliant with the DID Core Specification.

**Comment by ntn-x2** [comment]
The point is that one of the main critics to JSON-LD is that it tries to mix data linking with digital signatures, which serve two different purposes. Hence, using only integrity-protected links somehow addresses some of the shortcomings of using HTTP links in a JSON-LD context. Yes, we do have some HTTPs links ourselves, for now, but following your suggestion, the `Sr25519VerificationKey2020` would remain undefined.

**Comment by fabianekc** [comment]
Hi @ntn-x2 , I finally got to include JSON-LD validation based on https://www.npmjs.com/package/jsonld. For did:kilt this leads to a successful validation with the context
```
"@context": [
    "https://www.w3.org/ns/did/v1",
    "https://ipfs.io/ipfs/QmU7QkuTCPz7NmD5bD7Z7mQVz2UsSPaEK58B5sYnjnPRNW"
]
```
but ipfs:// is not yet supported as protocol by the jsonld npm package. As soon as it is supported there it will also validate here.
