### ISSUE TITLE
DID URI fragment in `verificationMethod` ID

### ISSUE THREAD

**Issue by bnewbold** [OwnYourData/didlint#5]
Apologies ahead of time if this ends up being a simple JSON-LD snafu on my part.

Using the current version of `didlint`, this DID Document fails to validate:

```
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/secp256k1-2019"
  ],
  "id": "did:plc:yk4dd2qkboz2yv6tpubpc6co",
  "verificationMethod": [
    {
      "id": "#atproto",
      "type": "EcdsaSecp256k1VerificationKey2019",
      "controller": "did:plc:yk4dd2qkboz2yv6tpubpc6co",
      "publicKeyMultibase": "zQYEBzXeuTM9UR3rfvNag6L3RNAs5pQZyYPsomTsgQhsxLdEgCrPTLgFna8yqCnxPpNT7DBk6Ym3dgPKNu86vt9GR"
    }
  ]
}
```

But if I turn the `verificationMethod` ID to the full-length format `did:plc:yk4dd2qkboz2yv6tpubpc6co#atproto`, it works. My understanding was that a fragment URI was allowed in that position; am I mistaken?

**Comment by fabianekc** [comment]
Yes, this is a recent update to the DID validation introduced a few days ago. The spec states:

> The value of the [id](https://www.w3.org/TR/did-core/#dfn-id) property for a [verification method](https://www.w3.org/TR/did-core/#dfn-verification-method) MUST be a [string](https://infra.spec.whatwg.org/#string) that conforms to the rules in Section [3.2 DID URL Syntax](https://www.w3.org/TR/did-core/#did-url-syntax).

In my interpretation of https://www.w3.org/TR/did-core/#fragment only "full" IDs are valid - as was also described by @iherman in the Draft [DID Core Vocabulary Shape](https://github.com/w3c/did-core/wiki/Draft-DID-Core-Vocabulary-Shape). I extended his proposed pattern `^did:[a-z0-9]+:[a-zA-Z0-9.-_]+` to `"^did:[a-z0-9]+:[a-zA-Z0-9.:\\-_%?=#]+$"`

Happy to get comments from other DID method authors and can easily change the behaviour!

**Comment by bnewbold** [comment]
Yeah, the ABNF seems clear, though relative/fragment URIs are often something of a special case in specs.

Thanks for the reply.
