### ISSUE TITLE
service property failing incorrectly

### ISSUE THREAD

**Issue by stormer78** [OwnYourData/didlint#7]
testing the following DID
did:web:mediator-nlb.storm.ws:mediator:v1:.well-known

**Reports**
Error in validating DID Document:
serviceEndpoint: there must be one 'serviceEndpoint' in 'service'

The document has multiple serviceEndpoint's defined in service and yet fails the test.

**Comment by fabianekc** [comment]
You are right, this was an error in DidLint validation spec. Thanks for the report!
DidLint updated and is now showing the example did:web as valid.

relevant DID Spec: https://www.w3.org/TR/did-core/#dfn-serviceendpoint

updated validation: https://soya.ownyourdata.eu/zQmSo2bV4HEbHy5WUSekvm5C91fRHp3her3cFSPYux9GgDB/yaml 
```
  serviceEndpoint:
    cardinality: "1..n"
    message: "invalid 'serviceEndpoint' in 'service'"
```

old validation: https://soya.ownyourdata.eu/zQmVqgXpgAhqCTBSX5GnJCq6z9HAJYrvd9pSzuUx8aujZWj/yaml
```
  serviceEndpoint:
    cardinality: "1..1"
    message: "there must be one 'serviceEndpoint' in 'service'"
```
